# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest
variables:
  DOCKER_HOST: 127.0.0.1:2375
  privileged: 'true'
services:
  - docker:dind

stages:
  - build-provisioning
  - deploy

build-provisioning:
  stage: build-provisioning
  only:
    - master
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE/provisioning:latest" ./provisioning
    - docker push "$CI_REGISTRY_IMAGE/provisioning:latest"

deploy_cloud:
  image: registry.gitlab.com/cncf/demo/provisioning:latest
  stage: deploy
  only:
    - aws
    - azure
    - gce
    - gke
    - packet
  environment:
    name: $CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com/
    on_stop: destroy_cloud
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./provisioning/data/
  script:
    - ./provisioning/provision.sh ${COMMIT_REF_NAME}-deploy ${CI_ENVIRONMENT_SLUG}

destroy_cloud:
  image: registry.gitlab.com/cncf/demo/provisioning:latest
  stage: deploy
  when: manual
  environment:
    name: $CI_PROJECT_NAME/$CI_COMMIT_REF_NAME
    action: stop
  artifacts:
    when: always
    expire_in: 4 weeks
    name: "${CI_ENVIRONMENT_SLUG}"
    paths:
    - ./provisioning/data/
  script:
    - ./provisioning/provision.sh ${COMMIT_REF_NAME}-destroy ${CI_ENVIRONMENT_SLUG}
