---
- yum_repository:
    name: docker
    description: Kubernetes Repository
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    gpgcheck: no
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg

- yum: name={{item} state=latest
  with_items:
    - kubernetes-cni
    - kubectl
    - kubelet
    - kubeadm

- service: name=kubelet enabled=yes state=running

- lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: 'Environment="KUBELET_EXTRA_ARGS=--cgroup-driver=systemd"'
    insertbefore: '^ExeStart='
