---
- get_url: url="{{ kubernetes_base_url }}/{{ item }}" dest=/usr/bin mode=a+x validate_certs=no force=true
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler
    - kube-proxy
    - kubelet
    - kubectl

- file: path=/etc/kubernetes state=directory mode=0755

- copy: src=etc/ dest=/etc/kubernetes mode=0644
- copy: src=services/ dest=/etc/systemd/system/ mode=0644

- name: generate certs
  command: /bin/sh /etc/kubernetes/make-ca-cert.sh _use_aws_external_ip_ IP:10.0.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local,DNS:masters.cncfdemo.k8s
  become: true

- service: name="{{ item }}" enabled=true
  with_items:
    - kube-apiserver
    - kube-controller
    - kube-proxy
    - kube-scheduler
    - kubelet
    - kube-addons
